version: 1
formatters:
  simple:
    format: '%(asctime)s:%(levelname)s:%(name)s:%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  logfile:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: /tmp/companies.log
loggers:
  dbclient:
    level: ERROR
  compapp:
    level: ERROR
  bin:
    level: ERROR
  werkzeug:
    level: ERROR
root:
  level: ERROR
  handlers: [logfile]

